### ISSUE TITLE
Is it work for time series metrics?

### ISSUE THREAD

**Issue by NitishRayar** [yesoreyeram/yesoreyeram-boomsummary-panel#13]
I want to show Aggregation cpu, memory, disk utilization using zabbix or grafana metrics. Metrics data is getting in timeseries and boomsummary table not support time series data.
 
How to resolve this one, please help some one.

**Comment by yesoreyeram** [comment]
No currently only table format. For time series check boomtable

**Comment by NitishRayar** [comment]
Thank you yesoreyeram, is it possible to do aggregation from boom table

**Comment by yesoreyeram** [comment]
Boom table dont do aggreation. but works will with time series data.  What is the usecase?
