### ISSUE TITLE
Getting "_this.$sce is undefined" 

### ISSUE THREAD

**Issue by knightsg** [yesoreyeram/yesoreyeram-boomsummary-panel#14]
I have a panel set up with a prometheus data source that I'm trying to use with boom table, but the panel is empty and reports an error, "_this.$sce is undefined". The boom table settings are all default, the metric I'm pulling from prometheus works if I change to a any other visualization type, and also returns valid series if I query directly in the prometheus interface.

I tried removing the boom table plugin and reinstalled via grafana-cli, removed and re-created the panel, but it shows the same error.

Grafana version: 6.5.0
Boom Table version: 1.3.0

**Comment by yesoreyeram** [comment]
Grafana 6.5 surfaced a bug which broke many third party plugins. Grafana team is fixing it https://github.com/grafana/grafana/issues/20662#event-2835352109

**Comment by knightsg** [comment]
Ok, good to know. Thanks!
