### ISSUE TITLE
Cell links

### ISSUE THREAD

**Issue by ianmoone** [yesoreyeram/yesoreyeram-boomsummary-panel#15]
Hi,

I've been using Boom Table for quite some time and I'm a big fan.
Boom summary panel is a big help as I need to work with table data.

My question is : would it be possible to define cell links as it is in Boom Table ?

**Comment by ianmoone** [comment]
up

**Comment by yesoreyeram** [comment]
Yes. U can define ur own custom html template. So u can have links or amy other HTML u needed.
