### ISSUE TITLE
Does this work with MYSql data base.

### ISSUE THREAD

**Issue by syedsfayaz** [yesoreyeram/yesoreyeram-boomsummary-panel#2]
@yesoreyeram   Hi, I was looking at this panel. I have a specific requirement where I need to drill down to more detail or different panel details. Does this panel support Mysql database as my data will be in mysql db. 

Is it possible to change the shape of the panel to a different one. I want to show a pipeline to show the progress of my software flow. from Dev --> qa --> uat --> prod. 

I replied to one of your comments on github so adding it here. 
https://github.com/Vonage/Grafana_Status_panel/issues/123#issuecomment-437352444

**Comment by yesoreyeram** [comment]
Yes this panel supports MySQL and any other table format . You may need some creativity and understanding of this panel. Optionally some HTML if you need some custom design. let me know how this goes. (This panel at very initial stage. So less documentation available. Also feel free to raise feature request / report bug.. )
