### ISSUE TITLE
Support String values in table. 

### ISSUE THREAD

**Issue by syedsfayaz** [yesoreyeram/yesoreyeram-boomsummary-panel#4]
@yesoreyeram   Does  this display multiple string values here.  In my case my table looks like this. 

![image](https://user-images.githubusercontent.com/26099918/62488149-75185c00-b778-11e9-8ee6-69af74f702c8.png)

I want to show applicationname(String), Buildnumber(String), Status(number), Stage(string)

**Comment by yesoreyeram** [comment]
Yes. That is possible.

**Comment by syedsfayaz** [comment]
I am currently having one issue in table panel where  I can hide a column but cannot use its values to change the color. Just wanted to check can we achieve it in this panel?

Can you also please share installation steps?

Attached a link for reference. 
https://community.grafana.com/t/hide-table-column-but-keep-the-rules/19918

**Comment by syedsfayaz** [comment]
@yesoreyeram   Can you please provide instructions on how to install this plugin.
