### ISSUE TITLE
Jumbo Stat with out title shows only one value. 

### ISSUE THREAD

**Issue by syedsfayaz** [yesoreyeram/yesoreyeram-boomsummary-panel#5]
@yesoreyeram 

I have installed the pluin and was able to pull data from the database. But I wanted to see every thing in one box. 

![image](https://user-images.githubusercontent.com/26099918/62756755-c7ce6e00-ba2d-11e9-8796-7aa88f530d89.png)

But when I choose a jumbo stats or jumbo stats without title. It shows me only one top value rather than all values. 

![image](https://user-images.githubusercontent.com/26099918/62756805-f51b1c00-ba2d-11e9-87ee-7ca4a111f7bb.png)

I also see a custom option. Does it take only html or I can use css as well.
![image](https://user-images.githubusercontent.com/26099918/62756867-20057000-ba2e-11e9-85f5-54f1571768bd.png)

Can you please tell me how I can see all the values.

**Comment by syedsfayaz** [comment]
Is it possible to change the shape of the square and make it like an arrow or some thing else?

**Comment by yesoreyeram** [comment]
Yea. Template supports CSS as well. But I haven't tested. You can write CSS to convert square into arrow

**Comment by yesoreyeram** [comment]
BTW, Jumpo stat is meant for single value only..

**Comment by syedsfayaz** [comment]
Is there a way I can see all 4 values in one single box like jumbo rather than seeing them in separate lines. How can I achieve it?

**Comment by yesoreyeram** [comment]
I think u r looking for #{statType,fieldName} token. Refer this in Readme file in the section called "tokens in templates"..

**Comment by syedsfayaz** [comment]
Yes, I was looking at it. I tried to print every thing in one block and it looks like this for now. May be I  need to work more on  this I guess.  I need it to be aligned in center. 

![image](https://user-images.githubusercontent.com/26099918/62795785-5d004f80-ba8c-11e9-8141-8e702566a7a9.png)

When I use title in the html it does not work for some reason. 
```
style="width:50%;float:left;padding:10px;">#{random,Setup,title}</div><br> 
            <div 
```
![image](https://user-images.githubusercontent.com/26099918/62795884-9cc73700-ba8c-11e9-8b57-5a4d5db40ca4.png)

**Comment by yesoreyeram** [comment]
Yes great. Keep going. Suggest you to put all the fields first without any html. Validate. And then add HTML styling..
