### ISSUE TITLE
Enable Drill Down to this plugin

### ISSUE THREAD

**Issue by syedsfayaz** [yesoreyeram/yesoreyeram-boomsummary-panel#7]
@yesoreyeram   I see generally we have a choice for drill down by providing a link or a different dashboard page. 
I want to link two different dashboards. 
Is there a choice to configure drill down on this dashboard. Where I can provide a different dashboard details when click user is redirected to a different page/dashboard.

**Comment by yesoreyeram** [comment]
Possibly can use <a> anchor tag in html template.

**Comment by syedsfayaz** [comment]
ok, Great. So I will explore html options.  So the values will be displayed as a link which is clickable. correct? 

I was thinking it as a new feature request. instead of a link the whole panel is clickable.

**Comment by yesoreyeram** [comment]
Thanks @syedsfayaz  for exploring this plugin. Feel free to close if the ticket is not necessary.  Any feedback appreciated.

**Comment by syedsfayaz** [comment]
@yesoreyeram  This is an amazing plugin. This came to rescue for me in difficult time. I have been searching for some custom plugin to show status of multiple environments. This is very close to what I am looking for. Additionally the html and css input you have enabled in it is very helpful for customization.

**Comment by syedsfayaz** [comment]
> Possibly can use anchor tag in html template.
Tried this and it works like a charm.  But I can only add one link.
